---
- name: Update and Upgrade APT Packages
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 86400 #24hrs

    - name: Upgrade all APT packages
      apt:
        upgrade: 'yes'
        force_apt_get: yes

