# Use an official Python runtime as a parent image
ARG TZ
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app/src

# Copy the current directory contents into the container at /app
COPY ./src ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run main.py when the container launches
CMD ["python3", "main.py"]
